Updates for Python 3.11 compatibility
ModOrganizer2/modorganizer-basic_games pull request #113
Opened 2023-09-16 02:39 UTC by Silarn

Some of this may also just be general cleanup for recent changes

2023-09-19 16:21 UTC, Holt59 commented
Is this still needed?

2023-09-19 17:37 UTC, Silarn commented
I think so, at least this all seems to be fixed for updates to pyqt6 and the differences in the pyi files as well as the necessary dependency version update for 3.11.

2023-09-19 18:05 UTC, Holt59 requested changes
Ok for me except for the `Optional` stuff that should use the new `| None` syntax.

2023-09-19 18:05 UTC, Holt59 commented on basic_features/basic_save_game_info.py
> +    def __init__(self, parent: QWidget, get_preview: Optional[Callable[[Path], Optional[QPixmap | Path | str]]]):
`Optional` should not be used anymore, you can use `| None` when needed. I don't think making `get_preview` optional is needed, simply default it to a `lambda p: None`. I thought this was already done in an existing PR 🤔

2023-09-19 18:05 UTC, Holt59 commented on basic_features/basic_save_game_info.py
> +    def __init__(self, get_preview: Optional[Callable[[Path], Optional[QPixmap | Path | str]]] = None):
Same comment as above for `Optional`.

2023-09-19 18:05 UTC, Holt59 commented on basic_features/basic_save_game_info.py
> +        self._get_preview: Optional[Callable[[Path], Optional[QPixmap | Path | str]]] = get_preview
No need to type here since `get_preview` (the parameter) is typed.

2023-09-19 18:07 UTC, Holt59 commented
Also, CI will probably fail for `| None` because the Python version needs to be updated to 3.11 in the workflow file.

2023-09-19 19:32 UTC, Silarn commented
I made the changes because my IDE was complaining that None was not supposed to be valid. I'll have to do this in a few hours.

2023-09-19 19:36 UTC, Holt59 commented
> I made the changes because my IDE was complaining that None was not supposed to be valid. I'll have to do this in a few hours.

I don't know what IDE you're using, but it's probably using a Python version lower than 3.10.

2023-09-24 07:02 UTC, Holt59 approved these changes

2023-09-24 07:03 UTC, merged